### ISSUE TITLE
test are not working

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/shard#27]
Mismatches on test output, some tests fail with errors

**Comment by rtsisyk** [comment]
- Sharding by primary keys - tests should be fixed (no excuses)
- Requests by secondary keys (map/reduce) - tests should be implemented (no excuses)
- node_down/join - tests should be fixed if it is possible in one working day, otherwise ping me
- Q operations - tests should be fixed if it is possible in one working day, otherwise ping me
- Re-sharding - this feature should be disabled/removed for now, I don't have time to fix it right now (see https://github.com/tarantool/shard/issues/37)

**Comment by rtsisyk** [comment]
1.1-91-g6ab67ee
